Bookstore CMS - MILESTONE FIVE UI
christianotieno/react-redux-bookstore pull request #5
Opened 2020-05-27 23:40 UTC by christianotieno

# Milestone 5: UI (see the following steps below for details)
## Dear reviewer, in this milestone, we carried out the following:

- [x] Review the provided design file from to identify all the elements.
- [x] Implement the styling of the different components based on the design.

##
We hereby welcome your timely review, thank you!

2020-05-28 03:22 UTC, bellom requested changes
## Hi Team :clap: 

### Awesome job so far!! :+1: 

You have done the basic, we just need to little more styling 🙏 so that your design can look almost the same as the project spec given:
But please Guys, we have strict guidelines as well to follow and one of the requirements is seeing into it that students replicated requirements.

If many students do this, we'll gradually shift away from the requirement from team to team.

Your design is very good, just not requirement-compliant, please try to adhere.THANKS
That's just why you don't get a thumbs up now.......

![image](https://user-images.githubusercontent.com/31897434/83092752-de65b480-a095-11ea-8196-989d7b7cd435.png)


![image](https://user-images.githubusercontent.com/31897434/80047697-0c3f6280-8506-11ea-9416-a4f1800e2329.png)


Let's work on the following:
1. I think you might want to reduce the height and the width of the `remove` button or kindly make use of the style from the original webpage provided by Microverse.
2. The `book `form` (you need to fix the height of the category and kindly make it similar to the original web page.) 
3. Kindly working on responsiveness, that's is; mobile view; category dropdown menu seems disappeared.
![image](https://user-images.githubusercontent.com/31897434/83092572-82029500-a095-11ea-8534-62aae9e3c70c.png)


### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**

2020-05-28 03:22 UTC, bellom commented on src/styles/scss/main.scss
> +  background-color: #0290ff;
you might want to apply the following;
1. `border-style: none`
2. `cursor: pointer`

before::
![image](https://user-images.githubusercontent.com/31897434/83095227-b167d080-a09a-11ea-8381-b55a846fd91f.png)


after:: 
![image](https://user-images.githubusercontent.com/31897434/83095105-8a110380-a09a-11ea-87e8-b809f7f92a85.png)

2020-06-04 04:18 UTC, Oghenebrume50 requested changes
### STATUS: CHANGES REQUIRED

Hi @christianotieno @collinsugwu good job team :+1:  everything is almost done except for a little design issue
![review](https://user-images.githubusercontent.com/37092867/83714407-90672880-a622-11ea-947c-5c14b1ab8b97.png)

From the screenshot above the "add book" button is not wide enough and also according to the original design, all the buttons have rounded edges. 

Please look into that :+1:  and request for another review :slightly_smiling_face: 

**RAPHAEL NORIODE** :mask:

2020-06-05 13:11 UTC, AdnanAfsari approved these changes
**Status: Approved**

Hello @christianotieno @collinsugwu ✋ 

Nice improvement,Looks good now so it's a 👍  from me.

Happy Coding
Adnan Afsari

2020-06-05 13:14 UTC, merged